name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Obtener carpeta modificada
        id: changed-directory
        uses: tj-actions/changed-files@v39
        with:
          files: '**/Dockerfile'

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image tags
        id: vars
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
          echo "TAG_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build Docker image with both tags
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.vars.outputs.TAG_SHA }} \
                       -t ${{ steps.vars.outputs.IMAGE_NAME }}:latest -f 'victorinox/Dockerfile' .

      - name: Push both image tags
        run: |
          docker push ${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.vars.outputs.TAG_SHA }}
          docker push ${{ steps.vars.outputs.IMAGE_NAME }}:latest

